[project]
name = "loading"
version = "0.1.0"
description = "Loading Programs"
authors = [
    {name = "andjajas"}
]
requires-python = ">=3.10"
dependencies = [
    "pandas (^3.0.6)",
    "matplotlib (^3.11.2)",
    "numpy (^2.5.3)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
